/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_SALESFORCE_LOGIN_URL: process.env.NEXT_PUBLIC_SALESFORCE_LOGIN_URL,
    NEXT_PUBLIC_SALESFORCE_CLIENT_ID: process.env.NEXT_PUBLIC_SALESFORCE_CLIENT_ID,
    NEXT_PUBLIC_SALESFORCE_CLIENT_SECRET: process.env.NEXT_PUBLIC_SALESFORCE_CLIENT_SECRET,
    NEXT_PUBLIC_SALESFORCE_USERNAME: process.env.NEXT_PUBLIC_SALESFORCE_USERNAME,
    NEXT_PUBLIC_SALESFORCE_PASSWORD: process.env.NEXT_PUBLIC_SALESFORCE_PASSWORD,
    NEXT_PUBLIC_SALESFORCE_SECURITY_TOKEN: process.env.NEXT_PUBLIC_SALESFORCE_SECURITY_TOKEN,
  },
}

module.exports = nextConfig 